/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/site-packages/transformers/utils/generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/site-packages/transformers/utils/generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `8`
		More than one GPU was found, enabling multi-GPU training.
		If this was unintended please pass in `--num_processes=1`.
	`--num_machines` was set to a value of `1`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/site-packages/transformers/utils/generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/site-packages/transformers/utils/generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/site-packages/transformers/utils/generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/site-packages/transformers/utils/generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/site-packages/transformers/utils/generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/site-packages/transformers/utils/generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/site-packages/transformers/utils/generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/site-packages/transformers/utils/generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/site-packages/transformers/utils/generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/site-packages/transformers/utils/generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/site-packages/transformers/utils/generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/site-packages/transformers/utils/generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/site-packages/transformers/utils/generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/site-packages/transformers/utils/generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/site-packages/transformers/utils/generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/site-packages/transformers/utils/generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
[rank5]: Traceback (most recent call last):
[rank5]:   File "/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank5]:     return _run_code(code, main_globals, None,
[rank5]:   File "/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/runpy.py", line 86, in _run_code
[rank5]:     exec(code, run_globals)
[rank5]:   File "/home/farinneya/eagle/eagle/train/main.py", line 98, in <module>
[rank5]:     from ..model.cnets import Model
[rank5]: ImportError: attempted relative import beyond top-level package
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank0]:     return _run_code(code, main_globals, None,
[rank0]:   File "/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/runpy.py", line 86, in _run_code
[rank0]:     exec(code, run_globals)
[rank0]:   File "/home/farinneya/eagle/eagle/train/main.py", line 98, in <module>
[rank0]:     from ..model.cnets import Model
[rank0]: ImportError: attempted relative import beyond top-level package
[rank0]:[W117 18:38:04.104818799 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
[rank4]: Traceback (most recent call last):
[rank4]:   File "/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank4]:     return _run_code(code, main_globals, None,
[rank4]:   File "/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/runpy.py", line 86, in _run_code
[rank4]:     exec(code, run_globals)
[rank4]:   File "/home/farinneya/eagle/eagle/train/main.py", line 98, in <module>
[rank4]:     from ..model.cnets import Model
[rank4]: ImportError: attempted relative import beyond top-level package
[rank7]: Traceback (most recent call last):
[rank7]:   File "/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank7]:     return _run_code(code, main_globals, None,
[rank7]:   File "/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/runpy.py", line 86, in _run_code
[rank7]:     exec(code, run_globals)
[rank7]:   File "/home/farinneya/eagle/eagle/train/main.py", line 98, in <module>
[rank7]:     from ..model.cnets import Model
[rank7]: ImportError: attempted relative import beyond top-level package
[rank3]: Traceback (most recent call last):
[rank3]:   File "/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank3]:     return _run_code(code, main_globals, None,
[rank3]:   File "/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/runpy.py", line 86, in _run_code
[rank3]:     exec(code, run_globals)
[rank3]:   File "/home/farinneya/eagle/eagle/train/main.py", line 98, in <module>
[rank3]:     from ..model.cnets import Model
[rank3]: ImportError: attempted relative import beyond top-level package
[rank2]: Traceback (most recent call last):
[rank2]:   File "/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank2]:     return _run_code(code, main_globals, None,
[rank2]:   File "/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/runpy.py", line 86, in _run_code
[rank2]:     exec(code, run_globals)
[rank2]:   File "/home/farinneya/eagle/eagle/train/main.py", line 98, in <module>
[rank2]:     from ..model.cnets import Model
[rank2]: ImportError: attempted relative import beyond top-level package
[rank6]: Traceback (most recent call last):
[rank6]:   File "/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank6]:     return _run_code(code, main_globals, None,
[rank6]:   File "/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/runpy.py", line 86, in _run_code
[rank6]:     exec(code, run_globals)
[rank6]:   File "/home/farinneya/eagle/eagle/train/main.py", line 98, in <module>
[rank6]:     from ..model.cnets import Model
[rank6]: ImportError: attempted relative import beyond top-level package
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank1]:     return _run_code(code, main_globals, None,
[rank1]:   File "/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/runpy.py", line 86, in _run_code
[rank1]:     exec(code, run_globals)
[rank1]:   File "/home/farinneya/eagle/eagle/train/main.py", line 98, in <module>
[rank1]:     from ..model.cnets import Model
[rank1]: ImportError: attempted relative import beyond top-level package
W0117 18:38:06.765000 3051468 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 3051712 closing signal SIGTERM
W0117 18:38:06.766000 3051468 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 3051713 closing signal SIGTERM
W0117 18:38:06.766000 3051468 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 3051714 closing signal SIGTERM
W0117 18:38:06.766000 3051468 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 3051717 closing signal SIGTERM
W0117 18:38:06.766000 3051468 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 3051719 closing signal SIGTERM
E0117 18:38:07.681000 3051468 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 3051711) of binary: /home/farinneya/miniconda3/envs/eagle2/bin/python
Traceback (most recent call last):
  File "/home/farinneya/miniconda3/envs/eagle2/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/site-packages/accelerate/commands/launch.py", line 970, in launch_command
    multi_gpu_launcher(args)
  File "/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/site-packages/accelerate/commands/launch.py", line 646, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/farinneya/miniconda3/envs/eagle2/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.main FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-01-17_18:38:06
  host      : lux-3-node-04
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 3051715)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2025-01-17_18:38:06
  host      : lux-3-node-04
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 3051716)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-01-17_18:38:06
  host      : lux-3-node-04
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3051711)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
